/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/optimized-room.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.06}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-177.112, 163.408, 4.468]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 106.681, 106.681]}>
            <mesh geometry={nodes.Cube001_Material009_0.geometry} material={materials['Material.009']} />
            <mesh geometry={nodes.Cube001_Material015_0.geometry} material={materials['Material.015']} />
          </group>
          <group position={[-126.901, 111.927, 49.502]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={115.302}>
            <mesh geometry={nodes.Cube003_Material009_0.geometry} material={materials['Material.009']} />
            <mesh geometry={nodes.Cube003_Material018_0.geometry} material={materials['Material.018']} />
          </group>
          <group position={[38.835, 88.123, -91.581]} rotation={[-1.93, 0, 0]} scale={[1.832, 0.515, 1.832]}>
            <mesh geometry={nodes.Cube011_Material020_0.geometry} material={materials['Material.020']} />
            <mesh geometry={nodes.Cube011_Material021_0.geometry} material={materials['Material.021']} />
          </group>
          <group position={[15.648, 88.123, -91.581]} rotation={[-1.93, 0, 0]} scale={[1.832, 0.515, 1.832]}>
            <mesh geometry={nodes.Cube012_Material020_0.geometry} material={materials['Material.020']} />
            <mesh geometry={nodes.Cube012_Material021_0.geometry} material={materials['Material.021']} />
          </group>
          <group position={[134.053, 88.123, -91.581]} rotation={[-1.93, 0, 0]} scale={[1.832, 0.515, 1.832]}>
            <mesh geometry={nodes.Cube018_Material020_0.geometry} material={materials['Material.020']} />
            <mesh geometry={nodes.Cube018_Material021_0.geometry} material={materials['Material.021']} />
          </group>
          <group position={[110.865, 88.123, -91.581]} rotation={[-1.93, 0, 0]} scale={[1.832, 0.515, 1.832]}>
            <mesh geometry={nodes.Cube019_Material020_0.geometry} material={materials['Material.020']} />
            <mesh geometry={nodes.Cube019_Material021_0.geometry} material={materials['Material.021']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane_Material011_0.geometry} material={materials['Material.011']} />
            <mesh geometry={nodes.Plane_Material012_0.geometry} material={materials['Material.012']} />
            <mesh geometry={nodes.Plane_PISO_0.geometry} material={materials.PISO} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Plane008_Material013_0.geometry} material={materials['Material.013']} />
            <mesh geometry={nodes.Plane008_Material014_0.geometry} material={materials['Material.014']} />
          </group>
          <group position={[215.489, 158.295, 99.716]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
            <mesh geometry={nodes.sign_neon_small_vert_Material006_0.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.sign_neon_small_vert_Material007_0.geometry} material={materials['Material.007']} />
          </group>
          <mesh geometry={nodes.BezierCurve001_Material023_0.geometry} material={materials['Material.023']} position={[49.159, 124.259, -40.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[160.997, 100, 100]} />
          <mesh geometry={nodes.BezierCurve002_Material023_0.geometry} material={materials['Material.023']} position={[49.159, 128.824, -40.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[160.997, 100, 100]} />
          <mesh geometry={nodes.BezierCurve004_Material023_0.geometry} material={materials['Material.023']} position={[49.159, 10.8, -35.883]} rotation={[-Math.PI / 2, 0, 0]} scale={[160.997, 100, 100]} />
          <mesh geometry={nodes.BezierCurve005_Material023_0.geometry} material={materials['Material.023']} position={[49.159, 10.8, -35.883]} rotation={[-Math.PI / 2, 0, 0]} scale={[160.997, 100, 100]} />
          <mesh geometry={nodes.Cube002_Material009_0.geometry} material={materials['Material.009']} position={[-52.145, 81.622, -17.052]} rotation={[-1.631, 0, 0]} scale={[1.236, 0.501, 1.236]} />
          <mesh geometry={nodes.Cube005_Material009_0.geometry} material={materials['Material.009']} position={[42.864, 60.927, -68.393]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 97.04]} />
          <mesh geometry={nodes.Cube007_Material_0.geometry} material={materials['Material.002']} position={[42.864, 135.98, -98.826]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 4.284, 100]} />
          <mesh geometry={nodes.Cube009__0.geometry} material={materials['Cube.009__0']} position={[247.399, 223.916, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[37.179, 102.267, 106.716]} />
          <mesh geometry={nodes.Cube013_Material019_0.geometry} material={materials['Material.019']} position={[247.399, 223.916, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[37.179, 102.267, 106.716]} />
          <mesh geometry={nodes.Cube015_Material009_0.geometry} material={materials['Material.009']} position={[138.082, 60.927, -68.393]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 97.04]} />
          <mesh geometry={nodes.Cube017_Material_0.geometry} material={materials['Material.002']} position={[138.082, 135.98, -98.826]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 4.284, 100]} />
          <mesh geometry={nodes.Curve_Material009_0.geometry} material={materials['Material.009']} position={[19.268, 182.88, -79.084]} scale={312.172} />
          <mesh geometry={nodes.Curve010_Material004_0.geometry} material={materials['Material.005']} position={[19.268, 182.88, -78.961]} scale={312.172} />
          <mesh geometry={nodes.Cylinder001_Material009_0.geometry} material={materials['Material.009']} position={[-66.216, 45.085, -16.261]} rotation={[-0.063, 0, 0]} scale={9.228} />
          <mesh geometry={nodes.Cylinder002_Material009_0.geometry} material={materials['Material.009']} position={[-66.216, 37.932, -2.78]} scale={9.228} />
          <mesh geometry={nodes.Plane004_Material013_0.geometry} material={materials['Material.013']} rotation={[-Math.PI / 2, 0, 0]} scale={[111.111, 100, 100]} />
          <mesh geometry={nodes.Plane005__0.geometry} material={materials['Cube.009__0']} rotation={[-Math.PI / 2, 0, 0]} scale={[111.111, 100, 100]} />
          <mesh geometry={nodes.Plane006__0.geometry} material={materials['Cube.009__0']} rotation={[-Math.PI / 2, 0, 0]} scale={[111.111, 100, 100]} />
          <mesh geometry={nodes.Plane014_Material001_0.geometry} material={materials['Material.001']} position={[-66.216, 5.419, -47.465]} rotation={[-Math.PI / 2, 0, 0]} scale={86.344} />
          <mesh geometry={nodes.Plane015_Material002_0.geometry} material={materials['Material.004']} position={[213.767, 137.051, -0.978]} rotation={[-Math.PI / 2, 0, 0]} scale={[57.163, 51.446, 51.446]} />
          <mesh geometry={nodes.Plane016_Material008_0.geometry} material={materials['Material.008']} position={[-66.216, 0, -47.465]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane017_Material003_0.geometry} material={materials['Material.003']} position={[-66.216, 0, -47.465]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Plane019_Material010_0.geometry} material={materials['Material.010']} rotation={[-Math.PI / 2, 0, 0]} scale={[111.111, 100, 100]} />
        </group>
      </group>
      <mesh geometry={nodes.Text.geometry} material={materials['Material.021']} position={[-0.59, 2.833, 1.153]} rotation={[1.572, 0, 0]} scale={0.396} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.025']} position={[0.877, 2.761, 1.123]} rotation={[-1.571, 1.568, -3.142]} scale={[0.4, 2.749, 1.536]} />
    </group>
  )
}

useGLTF.preload('/models/optimized-room.glb')
